### ISSUE TITLE
推荐公众号：深燃

### ISSUE THREAD

**Issue by cworld1** [ttttmr/wechat2rss#1]
## 公众号名称

深燃
（微信号：shenrancaijing）

## 主要领域

财经、热点解析

## 文章链接

[网红书店近黄昏](https://mp.weixin.qq.com/s/LENphK3BSufFj9IUqoF0SA)
[“饭圈”散去，还有2亿多人每天玩微博](https://mp.weixin.qq.com/s/nRx0PulAxB5vRuIci4gTmw)

## 简单描述

聚焦创新经济，专注深度内容。

**Comment by ttttmr** [comment]
#7 
https://www.myzaker.com/channel/23248
rsshub有zaker
