### ISSUE TITLE
输出全文RSS

### ISSUE THREAD

**Issue by yingziwu** [ttttmr/wechat2rss#10]
RSS feed 只有链接，没有全文

**Comment by ttttmr** [comment]
是的，只有链接和摘要

我目前是用阅读器获取全文

**Comment by yingziwu** [comment]
我感觉还是输出全文比较好。

>我目前是用阅读器获取全文

这里有几个问题：

- 很多RSS阅读器不支持提取全文功能，比如说：[Akregator](https://en.wikipedia.org/wiki/Kontact#News_Feed_Aggregator)
- 目前 RSS feed 输出的文章链接为 `?s` 参数的长链接，而非永久短链，链接可能存在未来失效之虞。而很多阅读器提取全文操作只在用户阅读时进行。这就可能造成历史Feed无法阅读问题。
    ![image](https://user-images.githubusercontent.com/22741471/144735613-50e8259c-fe53-4636-a85b-7d42f9ad5ac9.png)
- 404问题，RSS订阅一个功效便是防404。特别是微信公众号这样的经常删贴、封号的平台。

**Comment by ttttmr** [comment]
目前我是阅读时自动获取全文

链接失效的我目前没有遇到，怎么判断是否是永久链接？好像`?s`也有永久链接

404这个rss其实也不好解决，主要是时效性不高，目前大部分更新频率在12小时，404总会有人/站存的 https://web.archive.org 或者标题 Google 一下，一般都能解决

**Comment by yingziwu** [comment]
结论：微信公众号RSS Feed，还是收费服务靠谱。

**Comment by yingziwu** [comment]
全文输出还是非常还常有必要的。

**Comment by ttttmr** [comment]
目前这个服务能满足我的需求，我只尽力提供稳定可靠的免费服务

有高级需求要么自己动手，要么付钱别人做，要么等白嫖，和靠谱无关

个人对服务可靠性要求很高，谨慎加feat，全文输出暂时不考虑了

**Comment by yingziwu** [comment]
> 有高级需求要么自己动手
后端代码可以开源一下，以供参考吗？

**Comment by ttttmr** [comment]
暂时不会开源
