### ISSUE TITLE
[推荐公众号]: 经济学人双语精读

### ISSUE THREAD

**Issue by enlo1234** [ttttmr/Wechat2RSS#101]
### 公众号名称

经济学人双语精读

### 领域

英语学习

### 介绍

专注于外刊精读，偶尔有教学知识分享，主要用来提高中阶以上英语学习者的阅读理解与写作能力。
身边关注者多为同学/老师，苦于不方便在手机上边看文章边做笔记。

### 文章地址

《罗刹海市》到底在暗讽什么？丨经济学人报道
https://mp.weixin.qq.com/s/g1Eraw93vG1w5MoGfQCjXg

李玟生前控诉《中国好声音》丨时代周刊精读
https://mp.weixin.qq.com/s/-YdiokXI6OjYA-hEuz4wHg

如何形容“雨大”？
https://mp.weixin.qq.com/s/_c4UX7hpEv265Jy4zebiqg

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/3db1babbdeeb84327cf6b5315e98d5f40925ae13.xml
