### ISSUE TITLE
[推荐公众号]: 内德羽则说

### ISSUE THREAD

**Issue by JamYiz** [ttttmr/Wechat2RSS#102]
### 公众号名称

内德羽则说

### 领域

体育

### 介绍

足球相关的资讯、赛后复盘以及战术分析等

### 文章地址

http://mp.weixin.qq.com/s?__biz=MzA5ODg2MjE1OA==&mid=2655598854&idx=1&sn=f277cc0d0398863dd48ae1b36425afc2&chksm=8b368c27bc410531d2527184814544ab792ffd7031733182e7014e64a943c28741636adee394&mpshare=1&scene=23&srcid=0901HLhxA2p7sqozPbSYgWim&sharer_shareinfo=5947e8ca913a8699cff1370661f65206&sharer_shareinfo_first=5947e8ca913a8699cff1370661f65206#rd

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/25ab3bb01cf06dd921fa4887b4cb06c30dc11080.xml
