### ISSUE TITLE
[推荐公众号]: 长亭安全应急响应中心

### ISSUE THREAD

**Issue by getcode2git** [ttttmr/Wechat2RSS#106]
### 公众号名称

长亭安全应急响应中心

### 领域

网络安全

### 介绍

长亭安全应急响应中心致力于发布最新的漏洞风险提示与威胁情报，专注于网络安全领域的研究和解决方案。

### 文章地址

https://mp.weixin.qq.com/s/cgEAY34qyB0DG22JBdNxmg

**Comment by ttttmr** [comment]
这个已经有了，不过列表里的名字还是老的“长亭安全课堂” 

https://wechat2rss.xlab.app/feed/ae5cf9ab99ae03269527af0f7a6c05ff14d5863c.xml
