### ISSUE TITLE
[推荐公众号]: 安全学术圈

### ISSUE THREAD

**Issue by demonkit** [ttttmr/Wechat2RSS#108]
### 公众号名称

安全学术圈

### 领域

安全/学术

### 介绍

分享安全方面的论文、会议文章等

### 文章地址

https://mp.weixin.qq.com/s/gZZfuuQ_d6ISt9GQDNRNGA

https://mp.weixin.qq.com/s/EnGdEm0p6cXrdk42yrB90w

**Comment by ttttmr** [comment]
这个已经有了 https://wechat2rss.xlab.app/feed/8c5d5f0004e7231abeb01dac49cac5da4ec6933d.xml
