### ISSUE TITLE
推荐公众号：海边的西塞罗

### ISSUE THREAD

**Issue by wagsoft** [ttttmr/wechat2rss#11]
## 公众号名称

海边的西赛罗

## 主要领域

历史，时事

## 文章链接

https://mp.weixin.qq.com/s/Zobykf6N1CBorkPj18OH6A

## 简单描述

新出现的写手，历史现实交叉引证评论时事，质量较高

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/5e25483b324ae2d39510555465b12a2b2dfa4000.xml

**Comment by wagsoft** [comment]
非常感谢，不知道如何才能获取这个公众号自开设以来所有的文章rss？

**Comment by ttttmr** [comment]
> 非常感谢，不知道如何才能获取这个公众号自开设以来所有的文章rss？

这个我就不太清楚了，没有研究过
