### ISSUE TITLE
[推荐公众号]: 42章经

### ISSUE THREAD

**Issue by NeverChenX** [ttttmr/Wechat2RSS#114]
### 公众号名称

42章经

### 领域

创投

### 介绍

创投圈教科书式必读公号

### 文章地址

https://mp.weixin.qq.com/s?__biz=MzIyMDE5OTYyMw==&mid=2651050233&idx=1&sn=7420b1d821880b651e4cde881c0c8947&chksm=8c38df51bb4f564721f8072e8c3c9e8b6b9943277bb51dee7ef1e98c2c2beb097a5348831707&scene=21#wechat_redirect

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/31436fcc3bba8c2c2a9337a163afcb3b5a57a0a0.xml
