### ISSUE TITLE
[推荐公众号]: 傅盛

### ISSUE THREAD

**Issue by NeverChenX** [ttttmr/Wechat2RSS#115]
### 公众号名称

傅盛

### 领域

个人ip

### 介绍

创投

### 文章地址

https://mp.weixin.qq.com/s/mZ_CuSenJ7NX2zuy1C66DA

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/71257003d43d39b91ff9d38b6f3330c883dc8e0c.xml
