### ISSUE TITLE
[推荐公众号]: PaperWeekly

### ISSUE THREAD

**Issue by zyj20200** [ttttmr/Wechat2RSS#124]
### 公众号名称

PaperWeekly

### 领域

科技

### 介绍

PaperWeekly是一个推荐、解读、讨论和报道人工智能前沿论文成果的学术平台，致力于让国内外优秀科研工作得到更为广泛的传播和认可。

### 文章地址

https://mp.weixin.qq.com/s/Vp8w-MUZS6t01LCYjSWJJQ
https://mp.weixin.qq.com/s/P7d50eiv6syLTIQ9UoZHsw

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/3be891c2f4e526629ab055a297cc2cd6c1f0a563.xml
