### ISSUE TITLE
[推荐公众号]: CNNVD安全动态

### ISSUE THREAD

**Issue by xmzyshypnc** [ttttmr/Wechat2RSS#126]
### 公众号名称

CNNVD安全动态

### 领域

安全

### 介绍

中国信息安全测评中心为切实履行漏洞分析和风险评估的职能，负责建设运维的国家信息安全漏洞库，为我国信息安全保障提供基础服务。其中会推送最新的信息安全漏洞报告。

### 文章地址

[信息安全漏洞周报（2023年第51期）](https://mp.weixin.qq.com/s/SBBPDWrvz8_jbMPnAPY0_A)
[CNNVD关于Apache Dubbo 代码问题漏洞的通报](https://mp.weixin.qq.com/s/FVy6vzJK4CjeMS-d4dU2Fw)

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/899e0eaf0e3ea7abac0211b3db9bb39c616e3255.xml
