### ISSUE TITLE
[推荐公众号]: 

### ISSUE THREAD

**Issue by AresYoungLs** [ttttmr/Wechat2RSS#128]
### 公众号名称

阿里巴巴中间件+阿里技术

### 领域

编程技术

### 介绍

阿里巴巴中间件：阿里巴巴中间件团队官方账号，主要讲解云原生技术以及讨论问题解决思路
阿里技术：阿里技术管方账号，主要讲解编码思路，技术框架总结及最佳实践

### 文章地址

阿里巴巴中间件：《一文详解全栈可观测的实现路径》https://mp.weixin.qq.com/s/vpT7goLwamgJbkGqhlXXvA 
《启动速度提升 10 倍：Apache Dubbo 静态化方案深入解析》https://[mp.weixin.qq.com/s/8OjLmixbpBSnnIjGsdD0kg](https://mp.weixin.qq.com/s/8OjLmixbpBSnnIjGsdD0kg)
阿里技术：《好好的“代码优化”是怎么一步步变成“过度设计”的》 https://mp.weixin.qq.com/s/EGH9brDPcNbR3R3G6IaT0A
《慢SQL治理经验总结》https://mp.weixin.qq.com/s/YokYMEkM9WLKjm45OIGu7w

**Comment by ttttmr** [comment]
[阿里巴巴中间件](https://wechat2rss.xlab.app/feed/ede34e7a9aff5e93ad159ebfd27075710a963f54.xml)

[阿里技术](https://wechat2rss.xlab.app/feed/6e1f9b775f7a5841ac1a94310f0478b45a02ec01.xml)
