### ISSUE TITLE
推荐公众号：趋势交易的奶爸

### ISSUE THREAD

**Issue by ft3727754** [ttttmr/wechat2rss#13]
**在提交之前，请确认** #7

- [ ] 在[RSSHub](https://docs.rsshub.app/)上搜索，确认没有相关内容
- [ ] 在Google搜索作者/公众号相关内容，确认没有相关网站，或者作者在其他平台上发布内容

有Web页面，建议使用 https://feed43.com/ 制作RSS

有Web页面，但feed43不好获取，建议[给RSSHub提需求](https://github.com/DIYgod/RSSHub/issues)

## 公众号名称

xxx（用于搜索制作RSS）

## 主要领域

xxx（比如Web安全）

## 文章链接

xxx（用于制作RSS，以及评估推送文章质量）

## 简单描述

xxx（大概介绍一下公众号）

**Comment by ttttmr** [comment]
请完整填写内容
