### ISSUE TITLE
[推荐公众号]: 夕小瑶科技说

### ISSUE THREAD

**Issue by sherlcok314159** [ttttmr/Wechat2RSS#131]
### 公众号名称

夕小瑶科技说

### 领域

AI

### 介绍

主要讲 AI 方面的技术以及相关新闻

### 文章地址

- https://mp.weixin.qq.com/s/SZrIUS6t1D4DkIkqInadHA
- https://mp.weixin.qq.com/s/Nz3TPc0UX-ZJX38eOkzN2A

**Comment by ttttmr** [comment]
[夕小瑶科技说](https://wechat2rss.xlab.app/feed/a1cd365aa14ed7d64cabfc8aa086da40ecaba34d.xml)
