### ISSUE TITLE
[推荐公众号]: 集智俱乐部

### ISSUE THREAD

**Issue by sherlcok314159** [ttttmr/Wechat2RSS#132]
### 公众号名称

集智俱乐部

### 领域

AI，数学

### 介绍

进行科普以及对某些AI问题进行探讨

### 文章地址

- https://mp.weixin.qq.com/s/3AIm9w8l5bhTb59WkjAfTw
- https://mp.weixin.qq.com/s/iZP5b3R8bHO585irkS_eVw

**Comment by ttttmr** [comment]
[集智俱乐部](https://wechat2rss.xlab.app/feed/8540570d27c0bfe0a219173cf1ace83ae79445cb.xml)
