### ISSUE TITLE
[推荐公众号]: 量子位

### ISSUE THREAD

**Issue by sherlcok314159** [ttttmr/Wechat2RSS#134]
### 公众号名称

量子位

### 领域

AI

### 介绍

对 AI 方面的新闻进行报道

### 文章地址

- https://mp.weixin.qq.com/s/m5fEpI8kS0Hu5kCGVvz7_Q
- https://mp.weixin.qq.com/s/Z8IEWCMNeKxzDfDUnlxsiA

**Comment by ttttmr** [comment]
这个在很多平台/网站上有，就不加了
