### ISSUE TITLE
[推荐公众号]: 极市平台

### ISSUE THREAD

**Issue by sherlcok314159** [ttttmr/Wechat2RSS#136]
### 公众号名称

极市平台

### 领域

AI

### 介绍

对 AI 方面进行介绍

### 文章地址

- https://mp.weixin.qq.com/s/oDrSJUYKPgzIA-ntJEqFLg
- https://mp.weixin.qq.com/s/_gMYSiFMkYGLVmr0sF65UQ

**Comment by ttttmr** [comment]
目前主要关注原创，非转载的公众号

**Comment by sherlcok314159** [comment]
公众号存在转载现象是比较正常的，无论是转载还是原创，我觉得更应该侧重于文章的质量
