### ISSUE TITLE
如何转换为opml导入源

### ISSUE THREAD

**Issue by Lengso** [ttttmr/wechat2rss#14]
能整理一份opml文件吗，想导入feedly. 一个个太麻烦了。 

或者说有单一订阅接口？

**Comment by ttttmr** [comment]
是指全部rss吗？目前收录没有做分类，如果打包成一个的话，可能不太合适

或许能分技术，资讯等大类，师傅有空可以尝试分一下hhh

后面可以根据分类出opml文件

**Comment by Lengso** [comment]
对，主要是想白嫖师傅的hhhh

**Comment by ttttmr** [comment]
发现inoreader的合集可以导出opml

https://www.inoreader.com/reader/api/0/bundle/opml/0014cd641489

不过这个合集只收集了一部分

**Comment by Lengso** [comment]
多谢师傅～
