### ISSUE TITLE
订阅过来只有标题没有内容

### ISSUE THREAD

**Issue by KangodYan** [ttttmr/Wechat2RSS#144]
没有内容，只能点击标题进入源网址进行阅读，原本就是这样设计的吗

**Comment by ttttmr** [comment]
设计是如果公众号文章有摘要的话，会用摘要作为内容，不会获取全文

可以发下是哪个号，也不排除可能是bug

**Comment by KangodYan** [comment]
哦， 原来没有抓取全文昂，仔细看是有摘要的。。有两个号都有摘要，《猫笔刀》是不是没有摘要，我的这个源没有

**Comment by ttttmr** [comment]
猫笔刀没有摘要
