### ISSUE TITLE
[更新频率问题]免费的rss订阅抓取时间和实际时间差别很大

### ISSUE THREAD

**Issue by xmzyshypnc** [ttttmr/Wechat2RSS#151]
订阅抓取时间是4.6，发现文章实际时间为2月份，请问之后公开的rss免费订阅都会延迟抓取吗，只有私有化部署能保证和之前一样的更新频率吗？

**Comment by ttttmr** [comment]
是bug，文章创建时间赋值写错了，已修复，需要等待一段时间刷新

今天导致很多公众号出现了老文章也是这个问题

公开服务和私有化部署使用的程序的一样的，所有开发更新都会先发布到公开服务上，之后不定期给私有化发版本
