### ISSUE TITLE
[私有部署功能建议]：推荐集成更多的推送渠道，并增加tg bot自定义api url的环境变量

### ISSUE THREAD

**Issue by iskycc** [ttttmr/Wechat2RSS#153]
当前仅支持tg bot和server酱消息推送，推荐集成更多的推送渠道如钉钉、飞书、企业微信、邮件等，建议利用开源的集成推送项目如[message-pusher](https://github.com/songquanpeng/message-pusher)等降低多渠道维护成本。并且因为tg默认api url国内无法访问，建议新增一个环境变量填入反代好的国内可以访问的域名，通过此域名转发api请求

**Comment by ttttmr** [comment]
v1.0.14增加了webhook

https://wechat2rss.xlab.app/deploy/changelog.html#v1-0-14
