### ISSUE TITLE
[私有部署Bug反馈]：RSS内容中，资源链接的link字段url有两遍域名，如图

### ISSUE THREAD

**Issue by iskycc** [ttttmr/Wechat2RSS#157]
![image](https://github.com/ttttmr/Wechat2RSS/assets/81439128/aa7e09bd-a1ef-4579-b9e7-88a590b782bb)

**Comment by ttttmr** [comment]
已修复，下个版本发布带上

**Comment by ttttmr** [comment]
fixed v1.0.5
