### ISSUE TITLE
推荐公众号：长赢指数投资

### ISSUE THREAD

**Issue by yong-s** [ttttmr/wechat2rss#16]
**在提交之前，请确认** #7

- [ ] 在[RSSHub](https://docs.rsshub.app/)上搜索，确认没有相关内容
- [ ] 在Google搜索作者/公众号相关内容，确认没有相关网站，或者作者在其他平台上发布内容

有Web页面，建议使用 https://feed43.com/ 制作RSS

有Web页面，但feed43不好获取，建议[给RSSHub提需求](https://github.com/DIYgod/RSSHub/issues)

## 公众号名称

长赢指数投资

## 主要领域

金融基金投资

## 文章链接

https://mp.weixin.qq.com/s/O2_-TdGct3kFNQk4Xi6F-g

## 简单描述

指数化投资适合绝大多数人。利用市场估值与投资者情绪的变化，对指数长期持有，低买高卖，是普通投资者在资本市场获得财富的最佳方式。本公众号定期给出投资指数ETF的建议。主要是跟车搞钱（大概介绍一下公众号）

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/1f35edb36dfda13906f958fc3047e59ce9c234fe.xml
