### ISSUE TITLE
[Bug]: 私有部署代理接口的视频无法正常播放

### ISSUE THREAD

**Issue by iskycc** [ttttmr/Wechat2RSS#160]
### 版本

1.0.9

### 遇到的问题

私有部署的rss资源中，如果有视频，视频无法正常播放，播放按钮无法点击
![image](https://github.com/ttttmr/Wechat2RSS/assets/81439128/e023bd4d-77cb-49d8-94e3-0d0410a89b3b)

### 期望的结果

私有部署的rss资源中，如果有视频，视频可以正常播放，如果无法播放，日志中打印出原因，而非正常的200

### 日志

wechat2rss-rss  | [GIN] 2024/05/02 - 04:31:42 | 200 |   22.278179ms |    110.53.182.8 | GET      "/img-proxy?k=5e017db4&u=https%3A%2F%2Fmpvideo.qpic.cn%2F0bc3fqacqaaakmacowbsn5tfalgdfawaakaa.f10002.mp4%3Fdis_k%3Dbe2235520d44510d6197c86faa31bf5a%26dis_t%3D1714594844%26play_scene%3D10120%26auth_info%3DXpr3kt0ZGllk7fjY1w5wEUNiYk4xH1V0ak9IFiU4NVNkA04nKFpldBQIcnBXYD5rHDZwB2VXXw%3D%3D%26auth_key%3Dbd0681ae653bdd9c5d0fccad2b0ac1eb"

**Comment by ttttmr** [comment]
微信的视频链接是有时效的，刚爬下来是能看的，过期了就看不了

想要后面也能看的话，得把视频存起来

响应码这块确实需要该，应该403（因为微信回的403）

**Comment by iskycc** [comment]
这个问题没有一个好的解决办法吗

**Comment by ttttmr** [comment]
这个需要预先把视频缓存下来，比如存到数据库里

早些时候做了一版，跑了几天就快10G了，存储占用有点太高了，后面考虑限制只保留新的缓存，应该就好些了

**Comment by iskycc** [comment]
这个思路也不行啊，如果把视频缓存下来那就势必要用到本地的服务了，这样部署在cloudflare或者腾讯云函数的proxy代理就用不了了呢

**Comment by iskycc** [comment]
是否有能够实时获取视频直链的方法呢？

**Comment by ttttmr** [comment]
> 是否有能够实时获取视频直链的方法呢？

想了想也不是不行，就是比较麻烦，后面安排一下

**Comment by ttttmr** [comment]
v1.0.12已经加上了，可以更新试试

https://wechat2rss.xlab.app/deploy/changelog.html#v1-0-12
