### ISSUE TITLE
[推荐公众号]: Datawhale

### ISSUE THREAD

**Issue by xirong** [ttttmr/Wechat2RSS#164]
### 公众号名称

Datawhale

### 领域

编程-人工智能大模型

### 介绍

一个专注于AI领域的开源组织公众号，影响力很大，公众号发布一些优秀的文章和赛事资讯

### 文章地址

https://mp.weixin.qq.com/s/5_VnzP3JmOB0D5geV5HRFg
https://mp.weixin.qq.com/s/BV6afLLJNwtQeRd_9ZRWYw
https://mp.weixin.qq.com/s/C0KwNmsO9JbM-hxw6xga1g

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/4d620d988cb21cfeefd2263207221f0dc70df9ff.xml
