### ISSUE TITLE
[推荐公众号]: 也谈钱

### ISSUE THREAD

**Issue by Chidoudou** [ttttmr/Wechat2RSS#169]
### 公众号名称

也谈钱

### 领域

金融/生活方式

### 介绍

关于财务自由的各种干货与思考

### 文章地址

https://mp.weixin.qq.com/s?__biz=MzUzNjE3NzQ3Nw==&mid=2247489926&idx=1&sn=eac357cebcbfd7250828cdda88d9f122&chksm=fafb67accd8ceebaa1e750f129714bb000be9720a990a70c6fba6fc52fd3712014a58d699d6e&scene=178&cur_album_id=1319255999014043648#rd

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/f2fd5af8dc3590b99509f0c501de09066d063028.xml
