### ISSUE TITLE
推荐公众号：方方的航空小筑

### ISSUE THREAD

**Issue by windstander** [ttttmr/wechat2rss#18]
**在提交之前，请确认** #7

- [x] 在[RSSHub](https://docs.rsshub.app/)上搜索，确认没有相关内容
- [x] 在Google搜索作者/公众号相关内容，确认没有相关网站，或者作者在其他平台上发布内容

有Web页面，建议使用 https://feed43.com/ 制作RSS

有Web页面，但feed43不好获取，建议[给RSSHub提需求](https://github.com/DIYgod/RSSHub/issues)

## 公众号名称

方方的航空小筑

## 主要领域

军用航空

## 文章链接

https://mp.weixin.qq.com/s/QPXsyqPdj8xGCHuUttSzPA

## 简单描述

航迷自留地，专业人士公众号

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/b146ee0c6a719d7d3d86c93f4fdd4ca27b91baa2.xml
