### ISSUE TITLE
[Bug]: 2024/8/20公众号服务器更新又挂了

### ISSUE THREAD

**Issue by easonChen007** [ttttmr/Wechat2RSS#184]
### 版本

最新

### 遇到的问题

2024/8/20公众号信息没有更新,麻烦看看服务是不是出了问题

### 期望的结果

正常采集信息

### 日志

无

**Comment by ttttmr** [comment]
服务正常，没有挂

**Comment by easonChen007** [comment]
<img width="761" alt="image" src="https://github.com/user-attachments/assets/9cc28076-3540-4f5e-a237-7ccf6917ced9">
<img width="496" alt="image" src="https://github.com/user-attachments/assets/45189d24-a7f3-4db4-b8a5-a1d3c9794876">
但这个公众号无法更新，什么原因？

**Comment by ttttmr** [comment]
更新延迟24小时内都是正常的
