### ISSUE TITLE
[推荐公众号]: 量子位

### ISSUE THREAD

**Issue by qilinxiaoxiang** [ttttmr/Wechat2RSS#189]
### 公众号名称

量子位

### 领域

AI

### 介绍

AI新闻

### 文章地址

https://mp.weixin.qq.com/s/Ub0by14RBQQHnxtOnbXupg
https://mp.weixin.qq.com/s/Z-d-udJieOX2cnldFWTp9Q

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/7131b577c61365cb47e81000738c10d872685908.xml
