### ISSUE TITLE
推荐公众号：邱贞玮

### ISSUE THREAD

**Issue by windstander** [ttttmr/wechat2rss#19]
**在提交之前，请确认** #7

- [x] 在[RSSHub](https://docs.rsshub.app/)上搜索，确认没有相关内容
- [x] 在Google搜索作者/公众号相关内容，确认没有相关网站，或者作者在其他平台上发布内容

有Web页面，建议使用 https://feed43.com/ 制作RSS

有Web页面，但feed43不好获取，建议[给RSSHub提需求](https://github.com/DIYgod/RSSHub/issues)

## 公众号名称

邱贞玮

## 主要领域

原腾讯军事《踢馆》编辑，做军事分析

## 文章链接

https://mp.weixin.qq.com/s/hIMmf4k6zkAgeLu2pas99Q

## 简单描述

原腾讯军事《踢馆》编辑做的公众号，继续为广大军迷服务。

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/6451f06f5dffd44946bbdc407cf9605396f83437.xml
