### ISSUE TITLE
[推荐公众号]: 新智元

### ISSUE THREAD

**Issue by qilinxiaoxiang** [ttttmr/Wechat2RSS#190]
### 公众号名称

新智元

### 领域

AI

### 介绍

AI新闻

### 文章地址

https://mp.weixin.qq.com/s/0yIiWZK-ZiaOYYDSDRC5Tg
https://mp.weixin.qq.com/s/-s6LgtE-lw4wCqHYqaDtrw

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/ede30346413ea70dbef5d485ea5cbb95cca446e7.xml
