### ISSUE TITLE
[推荐公众号]: 思想钢印

### ISSUE THREAD

**Issue by Hanriver214** [ttttmr/Wechat2RSS#192]
### 公众号名称

思想钢印

### 领域

雪球年度影响力用户，私募基金经理

### 介绍

股市分析，金融史科普

### 文章地址

https://mp.weixin.qq.com/s/9I6IanRbq4ZH-GsLIu2FWQ
https://mp.weixin.qq.com/s/fCBQufeaq9be8j2hU-9EIg

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/a55006fab25a17c43a412246fda317822609f2ea.xml
