### ISSUE TITLE
[推荐公众号]: 集思路

### ISSUE THREAD

**Issue by Hanriver214** [ttttmr/Wechat2RSS#194]
### 公众号名称

集思路

### 领域

理财

### 介绍

低风险投资理财社区，精选文章分享

### 文章地址

https://mp.weixin.qq.com/s/l7OxjKsr92TgWWhfMsjq-A
https://mp.weixin.qq.com/s/ie7BSf6R4IicVEcbyC0XKw

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/f75bbb0bffd9fd6e0dda725282202ccc23a2bdff.xml
