### ISSUE TITLE
推荐公众号：澎湃明查

### ISSUE THREAD

**Issue by juzho6** [ttttmr/wechat2rss#2]
## 公众号名称：

澎湃明查

## 主要领域

新闻资讯、事实核查

## 文章链接

https://mp.weixin.qq.com/s/fRxh8UM5kYHC9_XoKZ4CYA

## 简单描述

对流传的资讯进行事实核查

**Comment by ttttmr** [comment]
#7 建议使用RSSHub

https://www.thepaper.cn/newsDetail_forward_111839
https://m.thepaper.cn/newsDetail_forward_15277547
