### ISSUE TITLE
推荐公众号：卢瑟经济学之安生杂谈

### ISSUE THREAD

**Issue by windstander** [ttttmr/wechat2rss#20]
**在提交之前，请确认** #7

- [x] 在[RSSHub](https://docs.rsshub.app/)上搜索，确认没有相关内容
- [x] 在Google搜索作者/公众号相关内容，确认没有相关网站，或者作者在其他平台上发布内容

有Web页面，建议使用 https://feed43.com/ 制作RSS

有Web页面，但feed43不好获取，建议[给RSSHub提需求](https://github.com/DIYgod/RSSHub/issues)

## 公众号名称

卢瑟经济学之安生杂谈

## 主要领域

经济、时政分析

## 文章链接

https://mp.weixin.qq.com/s/-ZU-GRlyMxoqSFaT0ACPvw

## 简单描述

作者是《纸牌屋》、《卢瑟经济学》作者

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/810c7b56b5341b3767e54b8648dc972c6b1f4fe9.xml

**Comment by ttttmr** [comment]
删号了，我这也删了
