### ISSUE TITLE
[推荐公众号]: 阿里云设计中心

### ISSUE THREAD

**Issue by crchenrun** [ttttmr/Wechat2RSS#201]
### 公众号名称

阿里云设计中心

### 领域

设计

### 介绍

阿里云设计中心是一支设计+技术+商业交叉融合的百人设计团队，致力于云计算科技领域的多元设计。在国内首次提出“计算设计”的概念，并在计算设计、数字孪生、数字设计、智能设计、体验设计、行业数字化转型和企业变革等领域中不断探索、实践、引领、进化。

### 文章地址

https://mp.weixin.qq.com/s/9Wk5Da8JDXaf5NtH82Fdiw
https://mp.weixin.qq.com/s/N30llDvrDhwtB1LvsstYkg

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/31e04606d37f684059e23a8fd3e05f1db0186495.xml
