### ISSUE TITLE
推荐公众号：小火箭

### ISSUE THREAD

**Issue by windstander** [ttttmr/wechat2rss#21]
**在提交之前，请确认** #7

- [x] 在[RSSHub](https://docs.rsshub.app/)上搜索，确认没有相关内容
- [x] 在Google搜索作者/公众号相关内容，确认没有相关网站，或者作者在其他平台上发布内容

有Web页面，建议使用 https://feed43.com/ 制作RSS

有Web页面，但feed43不好获取，建议[给RSSHub提需求](https://github.com/DIYgod/RSSHub/issues)

## 公众号名称

小火箭

## 主要领域

航空航天

## 文章链接

https://mp.weixin.qq.com/s/h5CtoJ30I3eaF0q1mg280A

## 简单描述

作者为邢强博士，航空航天专业。文章有深度，只是有段时间没有更新了。

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/ebbf3f8891e7d70626c75dca7b92dd6c075663d5.xml
