### ISSUE TITLE
[Bug]: 通过镜像站拉取docker 并部署 

### ISSUE THREAD

**Issue by Aibokalv** [ttttmr/Wechat2RSS#218]
### 版本

latest

### 遇到的问题

![image](https://github.com/user-attachments/assets/b026ee42-cc02-4865-8f41-959837c8baa5)

### 期望的结果

正常启动

### 日志

runtime/cgo: pthread_create failed: Operation not permitted
SIGABRT: abort
PC=0x7f2d0e3d09fc m=0 sigcode=18446744073709551610

goroutine 0 gp=0x1b65620 m=0 mp=0x1b66ee0 [idle]:
runtime: g 0 gp=0x1b65620: unknown pc 0x7f2d0e3d09fc
stack: frame={sp:0x7ffe73fdc4c0, fp:0x0} stack=[0x7ffe737dd000,0x7ffe73fdca20)
0x00007ffe73fdc3c0:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc3d0:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc3e0:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc3f0:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc400:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc410:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc420:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc430:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc440:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc450:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc460:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc470:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc480:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc490:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc4a0:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc4b0:  0x0000000000000000  0x00007f2d0e3d09ee 
0x00007ffe73fdc4c0: <0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc4d0:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc4e0:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc4f0:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc500:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc510:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc520:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc530:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc540:  0x0000000000000000  0x64aefa0b43ddfa00 
0x00007ffe73fdc550:  0x00007f2d0e337740  0x0000000000000006 
0x00007ffe73fdc560:  0x00007ffe73fdc890  0x0000000000000001 
0x00007ffe73fdc570:  0x0000000001b65620  0x00007f2d0e37c476 
0x00007ffe73fdc580:  0x00007f2d0e555e90  0x00007f2d0e3627f3 
0x00007ffe73fdc590:  0x0000000000000020  0x0000000000000000 
0x00007ffe73fdc5a0:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc5b0:  0x0000000000000000  0x0000000000000000 
runtime: g 0 gp=0x1b65620: unknown pc 0x7f2d0e3d09fc
stack: frame={sp:0x7ffe73fdc4c0, fp:0x0} stack=[0x7ffe737dd000,0x7ffe73fdca20)
0x00007ffe73fdc3c0:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc3d0:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc3e0:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc3f0:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc400:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc410:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc420:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc430:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc440:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc450:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc460:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc470:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc480:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc490:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc4a0:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc4b0:  0x0000000000000000  0x00007f2d0e3d09ee 
0x00007ffe73fdc4c0: <0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc4d0:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc4e0:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc4f0:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc500:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc510:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc520:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc530:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc540:  0x0000000000000000  0x64aefa0b43ddfa00 
0x00007ffe73fdc550:  0x00007f2d0e337740  0x0000000000000006 
0x00007ffe73fdc560:  0x00007ffe73fdc890  0x0000000000000001 
0x00007ffe73fdc570:  0x0000000001b65620  0x00007f2d0e37c476 
0x00007ffe73fdc580:  0x00007f2d0e555e90  0x00007f2d0e3627f3 
0x00007ffe73fdc590:  0x0000000000000020  0x0000000000000000 
0x00007ffe73fdc5a0:  0x0000000000000000  0x0000000000000000 
0x00007ffe73fdc5b0:  0x0000000000000000  0x0000000000000000 

goroutine 1 gp=0xc0000061c0 m=0 mp=0x1b66ee0 [running]:
runtime.systemstack_switch()
        runtime/asm_amd64.s:479 +0x8 fp=0xc000060750 sp=0xc000060740 pc=0x47c1a8
runtime.main()
        runtime/proc.go:172 +0x67 fp=0xc0000607e0 sp=0xc000060750 pc=0x43f4c7
runtime.goexit({})
        runtime/asm_amd64.s:1700 +0x1 fp=0xc0000607e8 sp=0xc0000607e0 pc=0x47e1c1

rax    0x0
rbx    0x7f2d0e337740
rcx    0xffffffffffffffff
rdx    0x6
rdi    0x7
rsi    0x7
rbp    0x7
rsp    0x7ffe73fdc4c0
r8     0x7ffe73fdc590
r9     0x7fffffff
r10    0x8
r11    0x246
r12    0x6
r13    0x16
r14    0x1b65620
r15    0x1ffffffffffffff
rip    0x7f2d0e3d09fc
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
 *  终端将被任务重用，按任意键关闭。

**Comment by ttttmr** [comment]
这是完整的日志吗？

和镜像站有什么关系吗？

**Comment by Aibokalv** [comment]
对应的截图和日志提github issue啦  辛苦大大看一下
微信也申请了










在 2024-11-29 15:34:56，"tmr" ***@***.***> 写道：

这是完整的日志吗？

和镜像站有什么关系吗？

**Comment by ttttmr** [comment]
看起来像docker的bug，升级一下docker试试？

**Comment by Aibokalv** [comment]
对  已经是完整的日志了 
这个是compose文件 
![image](https://github.com/user-attachments/assets/0ec5bf60-b5ce-4a47-bdda-2e6134af0794)

**Comment by Aibokalv** [comment]
Docker version 20.10.7, build f0df350
这是docker的版本  因为服务器应用比较多 不敢轻易升级

**Comment by ttttmr** [comment]
可能只能升级了

https://github.com/docker-library/golang/issues/467

> sloved by upgrate to docker 20.10.24

**Comment by Aibokalv** [comment]
好的好的  请问界面是这样的 正常否
![image](https://github.com/user-attachments/assets/ab6ded5e-36ff-46a8-8d02-5ae439901eef)
