### ISSUE TITLE
推荐公众号：Delphi研习社

### ISSUE THREAD

**Issue by coder163** [ttttmr/wechat2rss#22]
## 公众号名称

Delphi研习社

## 主要领域

Delphi原创文章

## 文章链接

https://mp.weixin.qq.com/s/78NkeWTItPfrFaz-EJhHfg

## 简单描述

可能是唯一一个还在坚持Delphi原创的公众号

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/d37a196db182852e509df92cdd89030481a2fa96.xml
