### ISSUE TITLE
[推荐公众号]: securitainment

### ISSUE THREAD

**Issue by cr1me0** [ttttmr/Wechat2RSS#223]
### 公众号名称

securitainment

### 领域

安全

### 介绍

文章技术技术深度较高，值得一读

### 文章地址

1. [横向移动 - NetNTLM 泄露仍是一个需要关注的问题](https://mp.weixin.qq.com/s/lqu1mnPr6gGcZrFr72OMmA)
2. [UDRL、SleepMask 和 BeaconGate](https://mp.weixin.qq.com/s/pqATYYscpdHQROxmTbPTcQ)

**Comment by ttttmr** [comment]
看了下基本都是翻译稿，选题质量不错

如果你是作者的话，建议注明一下翻译，也贴一下原文地址吧

https://wechat2rss.xlab.app/feed/8dd9857e540441b90ee86986df74b5e1a96d2abb.xml

**Comment by cr1me0** [comment]
谢谢大佬，我不是作者，我也感觉选题质量不错
