### ISSUE TITLE
推荐公众号：逻辑与经济现实

### ISSUE THREAD

**Issue by windstander** [ttttmr/wechat2rss#23]
**在提交之前，请确认** #7

- [x] 在[RSSHub](https://docs.rsshub.app/)上搜索，确认没有相关内容
- [x] 在Google搜索作者/公众号相关内容，确认没有相关网站，或者作者在其他平台上发布内容

有Web页面，建议使用 https://feed43.com/ 制作RSS

有Web页面，但feed43不好获取，建议[给RSSHub提需求](https://github.com/DIYgod/RSSHub/issues)

## 公众号名称

逻辑与经济现实

## 主要领域

经济数据分析

## 文章链接

https://mp.weixin.qq.com/s/Cd6oQiP6oi0v1HVVV2nLUw

## 简单描述

逻辑即规律，经济是如何与社会进行资源交易。逻辑与经济的融合，便可以理清交易的脉络与根源博弈，在现有规则下尽可能达成最有利自身的资源交易。

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/07cd3971227a35b5c35cd94d1961790dad9a87c7.xml
