### ISSUE TITLE
推荐公众号：从零开始定投日记

### ISSUE THREAD

**Issue by Writeup007** [ttttmr/wechat2rss#25]
## 公众号名称

从零开始定投日记

## 主要领域

基金定投跟投

## 文章链接
https://mp.weixin.qq.com/s/iuehrqzolUHIxBwahTA-9A（大佬自我介绍）
https://mp.weixin.qq.com/s/Ya6P87iYt-ME-BaWLdDnDw（平常发文）

## 简单描述

前同花顺员工，算是同花顺基金投资投顾服务中的核心人物，跟投基金对基金投资我等小白较友好。

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/0d2c5982deb01d2295ecf8f4891c9cb75d8d8ba3.xml
