### ISSUE TITLE
代码是否开源?

### ISSUE THREAD

**Issue by zhzy0077** [ttttmr/wechat2rss#27]
有一些个人关注的公众号 如所在街道的公告板等 关注量较小不适合消耗公共资源 如果代码开源的话可以自建

**Comment by ttttmr** [comment]
目前还没有计划开源，或许等到数量太多撑不住了会考虑（感觉快了hhh

**Comment by lufeirider** [comment]
请问下这个爬微信公众号文章原理是什么？是通过搜狗爬的吗？
