### ISSUE TITLE
推荐公众号：辉哥奇谭

### ISSUE THREAD

**Issue by feiyu517** [ttttmr/wechat2rss#28]
**在提交之前，请确认** #7

- [x] 在[RSSHub](https://docs.rsshub.app/)上搜索，确认没有相关内容
- [x] 在Google搜索作者/公众号相关内容，确认没有相关网站，或者作者在其他平台上发布内容

有Web页面，建议使用 https://feed43.com/ 制作RSS

有Web页面，但feed43不好获取，建议[给RSSHub提需求](https://github.com/DIYgod/RSSHub/issues)

## 公众号名称

辉哥奇谭（用于搜索制作RSS）

## 主要领域

个人成长

## 文章链接

[辉哥奇谭｜思想交易](https://mp.weixin.qq.com/s/-KpSeVFsBd_AfSaEKG5bLw)（用于制作RSS，以及评估推送文章质量）

## 简单描述

个人成长（大概介绍一下公众号）

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/1b01bd297483509251779f1a02bb90223786a923.xml
