### ISSUE TITLE
推荐公众号：关注米柚更新

### ISSUE THREAD

**Issue by juzho6** [ttttmr/wechat2rss#3]
## 公众号名称

关注米柚更新

## 主要领域

手机数码

## 文章链接

https://mp.weixin.qq.com/s/NcOk7TU_IBRfzYhb_I_ZDA

## 简单描述

收集MIUI系统每周的更新内容

**Comment by ttttmr** [comment]
#7 
rsshub有小米社区，不知道是不是同一个东西

**Comment by auto-bot-ty** [comment]
RSSHub小米社区是官方的, 公众号是个人整理的, 不是同一个东西

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/7391226cbd6ce8793e1e3d7d76b096bca336c571.xml
