### ISSUE TITLE
推荐公众号：凭栏欲言

### ISSUE THREAD

**Issue by windstander** [ttttmr/wechat2rss#31]
**在提交之前，请确认** #7

- [x] 在[RSSHub](https://docs.rsshub.app/)中搜索，确认没有相关内容
- [x] 在[Feeddd](https://feeddd.org/feeds)中搜索，确认没有相关内容
- [x] 在Google搜索作者/公众号相关内容，确认没有相关网站，或者作者在其他平台上发布内容

有Web页面，建议使用 https://feed43.com/ 制作RSS

有Web页面，但feed43不好获取，建议[给RSSHub提需求](https://github.com/DIYgod/RSSHub/issues)

## 公众号名称

凭栏欲言

## 主要领域

经济分析

## 文章链接

https://mp.weixin.qq.com/s/Lx9rJ0JiR2A65_GeT2NpRg

## 简单描述

对经济数据进行分析，结合经济史进行展望。

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/01c05fce74822ac6f30656f22e0ca542dfb7c8c0.xml
