### ISSUE TITLE
推荐公众号：路由器评测

### ISSUE THREAD

**Issue by windstander** [ttttmr/wechat2rss#36]
**在提交之前，请确认** #7

- [x] 在[RSSHub](https://docs.rsshub.app/)中搜索，确认没有相关内容
- [x] 在[Feeddd](https://feeddd.org/feeds)中搜索，确认没有相关内容
- [x] 在Google搜索作者/公众号相关内容，确认没有相关网站，或者作者在其他平台上发布内容

有Web页面，建议使用 https://feed43.com/ 制作RSS

有Web页面，但feed43不好获取，建议[给RSSHub提需求](https://github.com/DIYgod/RSSHub/issues)

## 公众号名称

路由器评测

## 主要领域

路由器

## 文章链接

https://mp.weixin.qq.com/s/q_wYad5NF5tTfMsoIJcYfA

## 简单描述

专注于评测路由器

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/2fa034e4b97f23d870d5b8e749e805d508761a41.xml
