### ISSUE TITLE
推荐公众号：先生制造

### ISSUE THREAD

**Issue by dae9300bac874828b23088dee1ec7290** [ttttmr/wechat2rss#4]
## 公众号名称

先生制造

## 主要领域

新闻采写

## 文章链接

https://mp.weixin.qq.com/s?__biz=MzAxNzQ5MDg2NA==&mid=2649617762&idx=1&sn=a5ed44daeacefa5fd6ac44b7961ec3c8&chksm=83fde3bdb48a6aabe79d297261c5877e2b689f4107e93321aa8a6f6148dabae3daf346879781

## 简单描述

《时尚先生》旗下的非虚构类新媒体

**Comment by ttttmr** [comment]
#7 
https://m.huxiu.com/member/3147695.html
建议用rsshub的虎嗅

**Comment by ttttmr** [comment]
虎嗅不太行，加上了 https://wechat2rss.xlab.app/feed/313326d41db4f54b1cc09e7c986a5ac4e5f88ca0.xml
