### ISSUE TITLE
https://wechat2rss.xlab.app

### ISSUE THREAD

**Issue by Spicy1chicken** [ttttmr/Wechat2RSS#41]
https://wechat2rss.xlab.app 不能访问了

**Comment by ttttmr** [comment]
![image](https://user-images.githubusercontent.com/32825326/178784390-8fb69198-5521-4231-bc29-d26fe21c72e9.png)

好像还好

**Comment by ttttmr** [comment]
最近发现vercel的免费流量有点撑不住了，今天加了一层cloudflare，后面观测一下能省多少流量吧

![image](https://user-images.githubusercontent.com/32825326/179447944-93a24756-d2a6-4e6d-b8e4-601b084649d9.png)

**Comment by ttttmr** [comment]
配置缓存之后省了98%的流量，继续用cloudflare了
