### ISSUE TITLE
推荐公众号：阿司匹林42195米

### ISSUE THREAD

**Issue by Prepanpan** [ttttmr/Wechat2RSS#57]
**在提交之前，请确认** #7

- [ ] 在[RSSHub](https://docs.rsshub.app/)中搜索，确认没有相关内容
- [ ] 在[Feeddd](https://feeddd.org/feeds)中搜索，确认没有相关内容
- [ ] 在Google搜索作者/公众号相关内容，确认没有相关网站，或者作者在其他平台上发布内容

有Web页面，建议使用 https://feed43.com/ 制作RSS

有Web页面，但feed43不好获取，建议[给RSSHub提需求](https://github.com/DIYgod/RSSHub/issues)

## 公众号名称

阿司匹林42195米（用于搜索制作RSS）

## 主要领域

医学法律科普，谣言粉碎机，美国生活（比如Web安全）

## 文章链接

https://mp.weixin.qq.com/s?__biz=MzUzMzkxOTc4NA==&mid=2247488586&idx=1&sn=22ac06e6f28720a8de745395693f0154（用于制作RSS，以及评估推送文章质量）

## 简单描述

由在美国工作的医生和律师撰写。医学法律科普，谣言粉碎机，美国生活（大概介绍一下公众号）

**Comment by ttttmr** [comment]
[阿司匹林42195米](https://wechat2rss.xlab.app/feed/644f104d713e906e00ad1c5a0f91db5374cb5fb1.xml)
