### ISSUE TITLE
推荐公众号：莫言

### ISSUE THREAD

**Issue by Prepanpan** [ttttmr/Wechat2RSS#58]
**在提交之前，请确认** #7

- [ ] 在[RSSHub](https://docs.rsshub.app/)中搜索，确认没有相关内容
- [ ] 在[Feeddd](https://feeddd.org/feeds)中搜索，确认没有相关内容
- [ ] 在Google搜索作者/公众号相关内容，确认没有相关网站，或者作者在其他平台上发布内容

有Web页面，建议使用 https://feed43.com/ 制作RSS

有Web页面，但feed43不好获取，建议[给RSSHub提需求](https://github.com/DIYgod/RSSHub/issues)

## 公众号名称

莫言（用于搜索制作RSS）

## 主要领域

莫言（比如Web安全）

## 文章链接

https://mp.weixin.qq.com/s/r3IheVr04eA5H0EETreZxg

## 简单描述

莫言的个人公众号（大概介绍一下公众号）

**Comment by ttttmr** [comment]
[莫言](https://wechat2rss.xlab.app/feed/c7f569a306308328f4d9c3ef5143087f13374311.xml)
