### ISSUE TITLE
推荐公众号：莫言读书会

### ISSUE THREAD

**Issue by Prepanpan** [ttttmr/Wechat2RSS#59]
**在提交之前，请确认** #7

- [ ] 在[RSSHub](https://docs.rsshub.app/)中搜索，确认没有相关内容
- [ ] 在[Feeddd](https://feeddd.org/feeds)中搜索，确认没有相关内容
- [ ] 在Google搜索作者/公众号相关内容，确认没有相关网站，或者作者在其他平台上发布内容

有Web页面，建议使用 https://feed43.com/ 制作RSS

有Web页面，但feed43不好获取，建议[给RSSHub提需求](https://github.com/DIYgod/RSSHub/issues)

## 公众号名称

莫言（用于搜索制作RSS）

## 主要领域

文学（比如Web安全）

## 文章链接

https://mp.weixin.qq.com/s/NqtEJXd-jVHYAFSXoiL38w

## 简单描述

本公号定期推送草言先牛擦权作品，并开展作品解
读、读者交流等活动
（大概介绍一下公众号）

**Comment by ttttmr** [comment]
[莫言读书会](https://wechat2rss.xlab.app/feed/6324f2c5d7c2413541a11589b64d7fcb63417ff7.xml)
