### ISSUE TITLE
推荐公众号：极昼工作室

### ISSUE THREAD

**Issue by dae9300bac874828b23088dee1ec7290** [ttttmr/wechat2rss#6]
在提交之前，请确认

- [x] 1. [RSSHub](https://docs.rsshub.app/)没有相关内容
- [x] 2. 没有可替代的Web页面

有Web页面，建议使用 https://feed43.com/ 制作RSS

有Web页面，但feed43不好获取，建议[给RSSHub提需求](https://github.com/DIYgod/RSSHub/issues)

## 公众号名称

极昼工作室

## 主要领域

新闻采写

## 文章链接

https://mp.weixin.qq.com/s?__biz=MzA3NTc2NDY5MA==&mid=2653063618&idx=1&sn=cfa3f99985a75581ceb502506cb56ddd&chksm=84bdaf7fb3ca2669026c6faa669248cf2a45c661cff32aafb575a5509c96291181293d7463be

## 简单描述

另一个严肃新闻工作室

**Comment by ttttmr** [comment]
#7 
已有RSS
https://posts.careerengine.us/author/5cf47f32b658c826083dba9f/posts
https://posts.careerengine.us/author/5cf47f32b658c826083dba9f/rss
