### ISSUE TITLE
推荐公众号：卢瑟经济学安生杂谈

### ISSUE THREAD

**Issue by windstander** [ttttmr/Wechat2RSS#60]
**在提交之前，请确认** #7

- [x] 在[RSSHub](https://docs.rsshub.app/)中搜索，确认没有相关内容
- [x] 在[Feeddd](https://feeddd.org/feeds)中搜索，确认没有相关内容
- [x] 在Google搜索作者/公众号相关内容，确认没有相关网站，或者作者在其他平台上发布内容

有Web页面，建议使用 https://feed43.com/ 制作RSS

有Web页面，但feed43不好获取，建议[给RSSHub提需求](https://github.com/DIYgod/RSSHub/issues)

## 公众号名称

卢瑟经济学安生杂谈

## 主要领域

经济、社会分析

## 文章链接
https://mp.weixin.qq.com/s/zxfrYrNc_C1HFOLDVXw8xQ

## 简单描述

是原“卢瑟经济学之安生杂谈”的备用号

**Comment by ttttmr** [comment]
[卢瑟经济学安生杂谈](https://wechat2rss.xlab.app/feed/62ec8c2ba29a16a45c8418a6ecd1945cc80eb380.xml)

**Comment by ttttmr** [comment]
号又没了

**Comment by windstander** [comment]
> 号又没了

唉，言论管制越来越紧了，他还有微博和星球、知乎的号还在。
