### ISSUE TITLE
推荐公众号：胡大一大夫

### ISSUE THREAD

**Issue by yeli008** [ttttmr/Wechat2RSS#62]
**在提交之前，请确认** #7

- [ ] 在[RSSHub](https://docs.rsshub.app/)中搜索，确认没有相关内容
- [ ] 在[Feeddd](https://feeddd.org/feeds)中搜索，确认没有相关内容
- [ ] 在Google搜索作者/公众号相关内容，确认没有相关网站，或者作者在其他平台上发布内容

有Web页面，建议使用 https://feed43.com/ 制作RSS

有Web页面，但feed43不好获取，建议[给RSSHub提需求](https://github.com/DIYgod/RSSHub/issues)

## 公众号名称

胡大一大夫

## 主要领域

医学: 心血管疾病

## 文章链接

https://mp.weixin.qq.com/s/tjcYMvHRKdFoTlJvbyKG6w

## 简单描述

心血管方面的国内顶级权威专家, 

现在家中老人或者中年人得心血管疾病的特别多, 现在已经成为危害人类健康的第一杀手, 严重的随时会危及到生命, 我想多了解一些这方面的预防以及治疗知识,对自己和家人都有好处. 看过他的一本书, 写的很好, 而且不推荐患者用很贵的药, 他的一句话我触动很深, 国内和美国顶级医院的差距不是技术, 而是治疗理念和思路,  目前只有微信公众号在更新,  自己研究过rss转出确实技术基础能力薄弱,无法独立完成rss输出,  rsshub提了,不过等待完成的项目实在太多,不抱希望. 请大佬帮忙,多谢.

**Comment by ttttmr** [comment]
链接预计2-3小时后可用

[胡大一大夫](https://wechat2rss.xlab.app/feed/711dd0c42a7a940c7438223ed2ee42131f6d555a.xml)
