### ISSUE TITLE
关于自己制作公众号rss订阅

### ISSUE THREAD

**Issue by yeli008** [ttttmr/Wechat2RSS#63]
tmr大佬, 请问如何基于你的脚本自己制作微信公众号的RSS订阅?

我是技术小白,现在主要通过自建rsshub订阅一些已有路由的自己感兴趣的rss.
微信公众号rss受限于自己基础薄弱, 搜了很多方法,都无法独立完成公众号rss输出.

如果每次总是在这里让大佬去帮我做,感觉很不好意思. 不知能否分享下自己制作公众号的方法或者有模板直接能套用吗?
望大佬指教, 多谢.

**Comment by psterman** [comment]
哈哈哈 你不是一个人

**Comment by ttttmr** [comment]
目前还没有办法自己制作，或者说self-hosted整个RSS服务

我现在的方案比较复杂，部署和使用上也有很多条件，可能不适合大多数人使用，也有一些开源的顾虑，可以参考 https://blog.xlab.app/p/a207c8e3/

技术参考 https://github.com/DIYgod/RSSHub/issues/311

**Comment by windstander** [comment]
怀念以前博客百花齐放都有feed的时代，甚至QQ空间都给了rss，现在也没了。

**Comment by ttttmr** [comment]
目前计划先以二进制/docker形式发布，支持自建，但不开源

等完成下面几个任务

- [ ] 不强绑定Telegram Bot管理数据，改为用http api管理
- [ ] 写一个web前端管理

**Comment by pengxy0** [comment]
@yeli008 请问下现在可以了么，我也想尝试下这个，但我也是小白hhh，想把公众号推送通过RSS订阅到Zotero，如果有好消息，可不可以告诉我一下下，谢谢啦

**Comment by yeli008** [comment]
> @yeli008 请问下现在可以了么，我也想尝试下这个，但我也是小白hhh，想把公众号推送通过RSS订阅到Zotero，如果有好消息，可不可以告诉我一下下，谢谢啦

依旧没有解决,期待大佬弄
