### ISSUE TITLE
提交新公众号前看这里

### ISSUE THREAD

**Issue by ttttmr** [ttttmr/Wechat2RSS#7]
微信公众号转RSS数量越多，越容易被封，为了能长久使用，能用其他代替的尽量代替

- [ ] 在[RSSHub](https://docs.rsshub.app/)上搜索，确认没有相关内容
- [ ] 在Google搜索作者/公众号相关内容，确认没有相关网站，或者作者在其他平台上发布内容

有Web页面，建议使用 https://feed43.com/ 制作RSS

有Web页面，但feed43不好获取，建议[给RSSHub提需求](https://github.com/DIYgod/RSSHub/issues)

如果某个RSS需求比较多，可以重新打开issues，利用emoji投票，+1比较多的可以不考虑以上条件
![image](https://user-images.githubusercontent.com/32825326/142764871-cb5f6f4f-05b2-48e0-bef7-8dc6c4512fd6.png)

提交新的公众号请新建issue，不要在其他地方评论

**Comment by xianliu263** [comment]
推荐公众号：阿虚同学

**Comment by ttttmr** [comment]
> 推荐公众号：阿虚同学

新建issues提交，不要在这里提交

**Comment by zhusuner** [comment]
推荐公众号: 新华社，央视新闻 ，人民日报

**Comment by gitous** [comment]
推荐公众号：渤海小吏的封建脉络百战

**Comment by ttttmr** [comment]
> 推荐公众号：渤海小吏的封建脉络百战

新建issues提交，不要在这里提交
