### ISSUE TITLE
推荐公众号：阿虚同学

### ISSUE THREAD

**Issue by xianliu263** [ttttmr/wechat2rss#8]
## 公众号名称

阿虚同学

## 主要领域

互联网生活指南

## 文章链接

http://mp.weixin.qq.com/s?__biz=MzA5NjEwNjE0OQ==&mid=2247503047&idx=1&sn=8569867c75cd1088aa056f14af146c1b&chksm=90b7af0da7c0261bb32c65d4db8401e51c3540bba809171f92695396e72da98f4e87c4d71c7e#rd)

## 简单描述

致力于生产收藏级的干货文章

**Comment by ttttmr** [comment]
这是自荐吗？

**Comment by kun2468** [comment]
半佛仙人
