### ISSUE TITLE
推荐公众号：红色安生

### ISSUE THREAD

**Issue by windstander** [ttttmr/Wechat2RSS#80]
**在提交之前，请确认** #7

- [x] 在[RSSHub](https://docs.rsshub.app/)中搜索，确认没有相关内容
- [x] 在[Feeddd](https://feeddd.org/feeds)中搜索，确认没有相关内容
- [x] 在Google搜索作者/公众号相关内容，确认没有相关网站，或者作者在其他平台上发布内容

有Web页面，建议使用 https://feed43.com/ 制作RSS

有Web页面，但feed43不好获取，建议[给RSSHub提需求](https://github.com/DIYgod/RSSHub/issues)

## 公众号名称

红色安生

## 主要领域

经济、政治分析

## 文章链接

https://mp.weixin.qq.com/s/-j2oPw03n0VhP_yNBisnwg

## 简单描述

卢瑟经济学之安生杂谈的后续公众号

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/e2379df83a2450a7dd45022f0408c65cdf11563f.xml
