### ISSUE TITLE
目前不考虑收录自荐

### ISSUE THREAD

**Issue by Test-Acount** [ttttmr/Wechat2RSS#82]
**在提交之前，请确认** #7

- [√] 在[RSSHub](https://docs.rsshub.app/)中搜索，确认没有相关内容
- [√ ] 在[Feeddd](https://feeddd.org/feeds)中搜索，确认没有相关内容
- [√ ] 在Google搜索作者/公众号相关内容，确认没有相关网站，或者作者在其他平台上发布内容

- [√ ] 有Web页面，建议使用 https://feed43.com/ 制作RSS

- [√ ] 有Web页面，但feed43不好获取，建议[给RSSHub提需求](https://github.com/DIYgod/RSSHub/issues)

## 公众号名称

悟空wukong
微信号：wkjckj

## 主要领域

检测认证、市场监管、食品安全领域

## 文章链接

[首个预包装食品GI标示标准发布，附标准全文](https://mp.weixin.qq.com/s?src=11&timestamp=1688606731&ver=4633&signature=2f3*xd8zJgeXiP9Jy*OB89*lxaZWJ0rq4NakTX8JvS-ta*lOCqSzXFyYiqCAMHKigveRlhI*MiO6FjTsFG5m3O44*RiScFFyLYwpFAgGr9eweLPQzqZCzhxH02sUoUyh&new=1)

## 简单描述

为检测认证、市场监管、食品安全领域提供行业最新资讯、专业知识共享及行业发展趋势解

**Comment by ttttmr** [comment]
链接过期了？
目前不考虑收录自荐
