### ISSUE TITLE
推荐公众号：阿虚同学

### ISSUE THREAD

**Issue by auto-bot-ty** [ttttmr/Wechat2RSS#83]
**在提交之前，请确认** #7

- [x] 在[RSSHub](https://docs.rsshub.app/)中搜索，确认没有相关内容
- [x] 在[Feeddd](https://feeddd.org/feeds)中搜索，确认没有相关内容
- [x] 在Google搜索作者/公众号相关内容，确认没有相关网站，或者作者在其他平台上发布内容

有Web页面，建议使用 https://feed43.com/ 制作RSS

有Web页面，但feed43不好获取，建议[给RSSHub提需求](https://github.com/DIYgod/RSSHub/issues)

## 公众号名称

阿虚同学

## 主要领域

互联网生活指南

## 文章链接

https://mp.weixin.qq.com/s/shRtoI0YD9GTpatcnbsxBA

## 简单描述

致力于生产收藏级的干货文章

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/808d3625c2b1915142f09e2d4bb2acd636aa956d.xml
