### ISSUE TITLE
推荐公众号：上海器审

### ISSUE THREAD

**Issue by terrytw** [ttttmr/Wechat2RSS#84]
**在提交之前，请确认** #7

- [x] 在[RSSHub](https://docs.rsshub.app/)中搜索，确认没有相关内容
- [x] 在[Feeddd](https://feeddd.org/feeds)中搜索，确认没有相关内容
- [x] 在Google搜索作者/公众号相关内容，确认没有相关网站，或者作者在其他平台上发布内容

## 公众号名称

上海器审

## 主要领域

医疗

## 文章链接

https://mp.weixin.qq.com/s/0RuZ4pmONHxg2i6SdZxMKg

## 简单描述

上海医疗器械审评中心公众号，介绍医疗器械新闻及科普。其内容不在官网上发布；通过Google搜索未发现有其他发布源。

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/7a292852e873eabf64cc2b76e0d883bae4306517.xml
