### ISSUE TITLE
[推荐公众号]: 机器学习初学者

### ISSUE THREAD

**Issue by Delreyaa** [ttttmr/Wechat2RSS#87]
### 公众号名称

机器学习初学者

### 领域

科技科普

### 介绍

[“机器学习初学者”公众号简介](https://mp.weixin.qq.com/s/I6_OC9Q7vqwRLFhYEA-soQ)

> 黄海广博士创办的公众号，黄海广博士个人知乎粉丝22000+，github排名全球前110名（32000+）。本公众号致力于人工智能方向的科普性文章，为初学者提供学习路线和基础资料。原创作品有：吴恩达机器学习个人笔记、吴恩达深度学习笔记等。

### 文章地址

[【深度学习】Transformer时间序列预测！](https://mp.weixin.qq.com/s/9uBJ1thCtC2JobC-JLQc-w)

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/c5f385197ef56f9345db0daf1e46419af8c7d664.xml
