### ISSUE TITLE
[推荐公众号]: 我爱计算机视觉

### ISSUE THREAD

**Issue by Delreyaa** [ttttmr/Wechat2RSS#88]
### 公众号名称

我爱计算机视觉

### 领域

科技

### 介绍

https://mp.weixin.qq.com/s/E-JcxA9gKs7DYNSZKazhOw

专注分享计算机视觉、机器学习、深度学习技术的最前沿，技术方向包括：OCR、SLAM、GAN、ReID、目标检测、语义分割、姿态估计、目标跟踪、人脸识别、行人检测、图像增强、超分辨率、三维重建、智能驾驶、神经架构搜索、医学影像处理与识别、遥感与航空影像处理识别、计算机视觉竞赛、CV职位内推信息等。

### 文章地址

https://mp.weixin.qq.com/s/EQHSoOIhGhe3-_autKKu2wl

**Comment by ttttmr** [comment]
文章地址打不开

**Comment by Delreyaa** [comment]
文章地址：https://mp.weixin.qq.com/s/EQHSoOIhGhe3-_autKKu2w

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/b81ffcfff1107b5265cd7e39de610dc7ca72caf4.xml
