### ISSUE TITLE
推荐公众号：python猫

### ISSUE THREAD

**Issue by xqhjay** [ttttmr/wechat2rss#9]
## 主要领域

编程IT

## 文章链接

https://mp.weixin.qq.com/s/SvUyyUGLZFbqEyERWWJIYQ

## 简单描述

分享Python进阶、Python哲学、文章翻译、资源工具等内容，大部分都是原创精品文章，被业界广泛转载

##
CSDN上也有，但RSShub没有收录

**Comment by ttttmr** [comment]
那可以直接在csdn上订阅啊 https://blog.csdn.net/chinesehuazhou2/rss/list
