### ISSUE TITLE
[推荐公众号]: Android 开发者

### ISSUE THREAD

**Issue by aitsuki** [ttttmr/Wechat2RSS#99]
### 公众号名称

Android 开发者

### 领域

编程

### 介绍

这个是Google官方的针对Android开发创建的公众号，提供Android开发相关的最新技术咨询、GooglePlay政策更新，也有来自社区用户的技术分享纹章。

### 文章地址

http://mp.weixin.qq.com/s?__biz=Mzk0NDIwMTExNw==&mid=2247554716&idx=1&sn=9b0931249c91b4eaf5776fd15703eb64&chksm=c32a1a6ef45d93783ff7ab365eb5c84e32f59c6556536c18fadd94a2089a180f7fea5f7de0eb&mpshare=1&scene=23&srcid=0817rEgicZPy1Am4NZHc8fCi&sharer_sharetime=1692242245744&sharer_shareid=1e51253059ad80f2e2437edc56b11960#rd

**Comment by ttttmr** [comment]
https://wechat2rss.xlab.app/feed/c2e44fa977abf95e4aabdd7059bbb8d1075a4720.xml
